version: '3'

dotenv:
  - .env

tasks:
  init:
    desc: Initialize environment
    silent: true
    cmds:
      - cp ./.env.dist ./.env || true
      - docker compose run --rm resume npm install
      - task: hooks:install

  run:
    desc: Start the application
    silent: true
    cmds:
      - docker compose up -d

  export:
    desc: Export resume (HTML)
    silent: true
    cmds:
      - docker compose run --rm resume npm run export

  export:pdf:
    desc: "Export resume as PDF in FR and EN — usage: task export:pdf"
    silent: true
    vars:
      FILENAME: 'david_piatek'
    cmds:
      - docker compose run --rm resume sh -c "PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser RESUME_PUPPETEER_NO_SANDBOX=1 npx resume export {{.FILENAME}}.pdf --theme=stackoverflow"
      - docker compose run --rm resume sh -c "PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser RESUME_PUPPETEER_NO_SANDBOX=1 npx resume export {{.FILENAME}}_en.pdf --theme=stackoverflow --resume resume.en.json"

  lint:
    desc: Lint Dockerfile and compose.yaml
    silent: true
    cmds:
      - hadolint Dockerfile
      - docker compose config --quiet

  test:
    desc: Validate resume.json
    silent: true
    cmds:
      - docker compose run --rm resume npm test

  hooks:install:
    desc: Install git hooks
    silent: true
    cmds:
      - git config core.hooksPath .githooks
      - chmod +x .githooks/pre-commit .githooks/pre-push
      - echo "Git hooks installed."

  default:
    desc: Default
    cmds:
      - task --list
