version: '3'

dotenv:
  - .env

tasks:
  init:
    desc: Initialize environment
    silent: true
    cmds:
      - cp ./.env.dist ./.env || true
      - docker compose run --rm resume npm install
      - task: hooks:install

  run:
    desc: Start the application
    silent: true
    cmds:
      - docker compose up -d

  export:
    desc: Export resume
    silent: true
    cmds:
      - docker compose run --rm resume npm run export

  lint:
    desc: Lint Dockerfile and compose.yaml
    silent: true
    cmds:
      - hadolint Dockerfile
      - docker compose config --quiet

  test:
    desc: Validate resume.json
    silent: true
    cmds:
      - docker compose run --rm resume npm test

  hooks:install:
    desc: Install git hooks
    silent: true
    cmds:
      - git config core.hooksPath .githooks
      - chmod +x .githooks/pre-commit .githooks/pre-push
      - echo "Git hooks installed."

  default:
    desc: Default
    cmds:
      - task --list
