version: '3'

dotenv:
  - .env

tasks:
  init:
    desc: Initialize environment
    silent: true
    cmds:
      - cp ./.env.dist ./.env || true
      - docker compose run --rm  resume npm install

  run:
    desc: Start the application
    silent: true
    cmds:
      - docker compose up -d

  export:
    desc: Export
    silent: true
    cmds:
      - docker compose run --rm  resume npm run export

  default:
    desc: Default
    cmds:
      - task --list
